### ISSUE TITLE
Cannot enter rooms / Major / Human Player & Computer Player

### ISSUE THREAD

**Issue by Gmunster33** [zmader/Clue#10]
While playing, despite how many moves the player may have left, both the computer player and the human player seem physically unable to enter rooms past the entrance. Both of the players are walking around the corridors and standing in the first square of the room but are not able to enter, peruse the rooms, or access the secret passageways. 
In order to recreate this bug, attempt to enter a room with extra moves remaining that turn. The player will not be able to enter further, nor move to the passageways.

**Comment by Kai-Richardson** [comment]
This is intended functionality. You cannot move inside a room once you enter a room, since it all counts as one tile.
